#!/usr/bin/env bash

# set the keymap

print(){
	printf '%s' "$1"
}

println(){
	printf '%s\n' "$1"
}


# localectl list-keymaps
print "choose your keymap: "
read KEYMAP
loadkeys "$KEYMAP"

print "connect with the internet: "
nmtui 

# timedatectl list-timezones
print "choose your timezone: "
read TIMEZONE
timedatectl set-timezone "$TIMEZONE"

print "create your partitions!"
print "opening cfdisk..."
cfdisk

print "tell me the partitions"
read BOOT # mount on /boot
read SWAP # mount with swapon /dev/swap_partition
read ROOT # mount on /
# read HOME

# create filesystems
print "creating your partitions filesystems"
mkfs.ext4 "$ROOT"
mkswap "$SWAP"
mkfs.fat -F 32 "BOOT"

# mounting filesystems
print "mouting your partitions"
mount "$ROOT" /mnt
mount --mkdir "$BOOT" /mnt/boot
swapon "$SWAP"

pacstrap -K /mnt base linux linux-firmware intel-ucode

genfstab -U /mnt >> /mnt/etc/fstab

bootctl install --path /mnt/boot
echo "default arch.conf" >> /mnt/boot/loader/loader.conf
cat <<EOF > /mnt/boot/loader/entries/arch.conf
title Tortoise Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options root=${ROOT} rw
EOF

arch-chroot /mnt
ln -sf /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime
hwclock --systohc

print "uncoment your locale."
micro /etc/locale.gen
locale-gen
echo "LANG=pt_BR.UTF-8" /etc/locale.conf
echo "KEYMAP=$KEYMAP" >> /etc/vconsole.conf

print "choose your hostname:"
read HOSTNAME
echo "$HOSTNAME" >> /etc/hostname

print "choose root password: "
passwd
